version: '3'
services:
  huawei-solar:
      build: '.'
      container_name: huawei-solar
      restart: unless-stopped
      image: huawei-solar:latest
      environment:
        - "INVERTER_IP=${INVERTER_IP}"
        - "INVERTER_PORT=${INVERTER_PORT:-6607}"
        - "MQTT_HOST=${MQTT_HOST}"
        - "MQTT_USER=${MQTT_USER}"
        - "MQTT_PASS=${MQTT_PASS}"
